### ISSUE TITLE
Integration of method for recieving usage information

### ISSUE THREAD

**Issue by BoxSo** [GillesWHC/deepl-client#13]
Would it be possible to implement a method to get the usage information from deepl?

[https://api.deepl.com/v2/usage?auth_key=[Auth_key]](https://api.deepl.com/v2/usage?auth_key=[Auth_key])

This returns a json with translated characters and the defined limit:

```
{
"character_count": 1365380,
"character_limit": 4000000
}
```

**Comment by GillesWHC** [comment]
Sure! I'll add this tomorrow!

**Comment by GillesWHC** [comment]
@BoxSo I added the method and published the package. Could you let me know if it works for you? Thanks!

**Comment by GillesWHC** [comment]
Closing due to no response form the original issue author. If anyone needs help with this, don't hesitate to reopen!
