### ISSUE TITLE
Support translating multiple texts

### ISSUE THREAD

**Issue by rawroland** [GillesWHC/deepl-client#15]
I am currently building an on the fly translation for an api which may have a lot of separate text blocks to translate. This does not scale very well if I have to create a separate translation promise for each text block. A suitable alternative could be to use the [Large volumes of text feature](https://www.deepl.com/docs-api/translating-text/large-volumes/).

This can be quickly achieved by changing the type definition for `TranslationParameters::text` to a union type of `string | string[]`. I would be ready to create a pull request for such a change if you are interested.

Thanks for the awesome package.

**Comment by GillesWHC** [comment]
Due to the restrictions set by the DeepL team, adding support for multiple translations sadly isn't as easy as changing the `string` type to a union consiting of `string` & `string[]`. I've been thinking, and I think the following approach would work.

We could create a new function called `translateMultiple`, which takes `TranslationParameters` and `string[]` as arguments. Just like we do now, we map the parameters as query string, and then check if the `string[]` contains 50 strings or less (a restriction defined by the DeepL API). Afterwards, we could loop over the array and for every entry, we could add `text=entry` to the query string.

Would this work for you? Thanks for creating the issue!!

**Comment by rawroland** [comment]
That sounds like a perfect alternative. I can, like I said, create a pull request with your suggested changes. Thanks for the fast response.

**Comment by GillesWHC** [comment]
I can do it tonight or tomorrow, I'll let you know when it's published!

**Comment by rawroland** [comment]
Sounds good. Thank you.

Gilles <notifications@github.com> schrieb am Fr., 13. Nov. 2020, 15:03:

**Comment by rawroland** [comment]
I was just playing around with the request and ran into an HTTP 414 error (Request-URI Too Large). Maybe we should consider using a `POST` request in the `translateMultiple` function.

**Comment by GillesWHC** [comment]
Oh yeah I didn't account for that, I'll change the existing ones to use the post method as well! Thanks!

**Comment by GillesWHC** [comment]
@rawroland You can try the `translateMultiple` function with the `10.0.12-beta.0`. Let me know if this works for you and I'll merge it into the normal release. I also changed the fetch method to POST, so the API won't throw a 414 anymore.

**Comment by rawroland** [comment]
@GillesWHC The `translateMultiple` method functions as expected and the HTTP 414 error does not exhibit anymore. I however am receiving a new error: "error: FetchError: invalid json response body at ...".  My content has html tags, with some even beginning HTML Tags. An example follows:

`<p>Some content</p>`

**Comment by rawroland** [comment]
@GillesWHC Could it be possible to export the type `TranslationResponse` along with the other types?

**Comment by GillesWHC** [comment]
Will do! I'll take a look at it right away.

**Comment by GillesWHC** [comment]
I cannot reproduce the `"error: FetchError: invalid json response body at ..."` error. Could you check your network tab and see the exact response from the API? I published `10.0.12-beta.1` which exports all the types.

**Comment by rawroland** [comment]
@GillesWHC I found the error. It had nothing to do with the html tags within the texts, but rather request uri which was still too long. I made the following changes to the `translateMultiple` method which solved the problem:

```typescript
export async function translateMultiple(
  params: TranslationMultipleParameters,
  text: string[],
): Promise<TranslationResponse> {
  if (text.length < 1) throw 'Text array was empty. No text to translate.';
  if (text.length > 50) throw 'Text array contained more than 50 strings. This is a restriction of the DeepL API.';

  const body = querystring.stringify({
    ...params,
    text,
  });
  const response = await fetch(`https://api.deepl.com/v2/translate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  });

  if (!response.ok) throw `Something went wrong. Are you using a valid authorization key? (${await response.json()})`;

  return response.json();
}
```

I use the querystring.stringify method to prepare the request body with the following snippet:
```typescript
const body = querystring.stringify({
  ...params,
  text,
});
```

I then adjust the post request to use the request body and not the query parameters. It was very important not to forget the `Content-Type` header.
```typescript
const response = await fetch(`https://api.deepl.com/v2/translate`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body,
});
```

I hope this helps to clarify the issue.

**Comment by GillesWHC** [comment]
Oh wow, what an oversight on my end, not using the post body, sorry! I'm implementing your changes right now. I'll let you know when I publish the package!

**Comment by GillesWHC** [comment]
Allright, I implemented your code and updated the other functions to match. I tested it locally and everything seems to work. Let me know if it works for you, then I'll publish a stable version!

**Comment by rawroland** [comment]
Just tried it. Works like a charm 👍🏾.

I had another issue with the `fetch` method provided by `cross-fetch`. The function is not available in `node`, which caused problems. I currently have a workaround, using [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch). Would this be an issue you would want to fix? I suggest that we close this issue with the solution we have now and open another issue for that if you think it is necessary.

**Comment by rawroland** [comment]
Another unrelated question: are you planning on adding a [sponsor button](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository). Would like to contribute to your open source contribution.

**Comment by GillesWHC** [comment]
I'll just change cross-fetch back to node fetch, as I haven't had anyone comment on the fetch method not working correctly. It was just a change I thought might improve compatibility. I'll revert the change and publish the package. Thanks for opening the issue!

**Comment by GillesWHC** [comment]
Haven't really thought about adding a sponsor button, I'll think about it. Thanks for the compliment though, and thanks again for opening the issue!
