### ISSUE TITLE
Add formality feature to list of parameters

### ISSUE THREAD

**Issue by TheFive** [GillesWHC/deepl-client#7]
From Deepl API 
https://www.deepl.com/docs-api/translating-text/request/

formality | Optional | Sets whether the translated text should lean towards formal or informal language. This feature currently only works for "DE (German)", "NL (Dutch)" and "PL (Polish)" as target language.Possible options are: "default" (default)"more" - for a more formal language"less" - for a more informal language
-- | -- | --

**Comment by GillesWHC** [comment]
Sorry for the delayed response! Support for the parameter has been published!

**Comment by TheFive** [comment]
Thank you, your Wrapper is very helpfull.
